# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbca13bb36b3a5abc606da486202c4df92ff479bd8c041fe86a9873c328816850900a0e43cc580420e616d7765b90ebd689b05cc8706a9693729067c7c8ab5d3

test:
  secret_key_base: 4fa2a00dab90a6b914ad3b13c70e95eaaf76d6fae6241a8ecec789eb9515cb074b5d8782fbb5d6fa2d860188e74d72a4a63093f4e0d6a81d3b6381ad51edf8c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
